import React from "react";
import Header from "../header/Header";
import Footer from "../footer/Footer";
import Head from "next/head";
interface Props {
    children: React.ReactNode;
}
function LayoutComponent({ children }: Props) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css" rel="stylesheet"></link>
            </Head>
            <Header />
            <div className="max-width">{children}</div>
            <Footer />
        </>
    );
}

export default LayoutComponent;
